# Skip initializing any tools in the DefaultEnvironment 
# as we're not using it.
DefaultEnvironment(tools=[])

env = Environment(LIBPATH=['.'])

libname = 'xyz'
env.SharedLibrary(
    target = libname,
    source = 'lib.c')
    
# We list the library by it's base name 'xyz' and not xyz.dll, or libxyz.a because SCons
# will expand this to the appropriate platform/compiler dependent file name 
# and use the correct arguments to the linker to link against the shared library 'xyz'
# NOTE: We use LIBS here instead of env['LIBS']=['xyz'] as we're also building the
#       shared library above with the same Environment().
#       Having env.Prepend(LIBS=['xyz']) would cause the SharedLibrary() above to ALSO
#       try to link against shared library xyz. (Or on win32 file 'xyz.lib') and fail.
env.Program(
    target = 'app',
    source = 'app.c',
    LIBS=[libname,])
