# Skip initializing any tools in the DefaultEnvironment 
# as we're not using it.
DefaultEnvironment(tools=[])

env=Environment()

conf=Configure(env, config_h='config.h')
conf.Define('FUNNY_STUFF')
conf.Finish()
