# Skip initializing any tools in the DefaultEnvironment 
# as we're not using it.
DefaultEnvironment(tools=[])

env=Environment()

env['CPPPATH'] = ['#/src/liba']
env['CPPDEFINES']=[('FLAVOR','vanilla')]

SConscript('src/SConscript', variant_dir='build/vanilla', exports='env')

choc_env = env.Clone(CPPDEFINES=[('FLAVOR','chocolate')])
SConscript('src/SConscript', variant_dir='build/chocolate', exports={'env':choc_env})
